### ISSUE TITLE
Tests with unmet requirements take space in progress bar

### ISSUE THREAD

**Issue by vmalloc** [getslash/backslash#107]
Migrated from BACKSLASH-49

**Comment by ayalash** [comment]
BACKSLASH-49 was created at 06/Jan/16 11:45. Its description:
> I would expect these tests to not be counted when showing the progress bar.

I think that this issue is obsolete, because I'm not aware of any progress bar which is exist in current version. 

@drrlvn Do you remember which progress bar you referred to?

**Comment by drrlvn** [comment]
There's no longer a "progress bar" in the new UI.
