### ISSUE TITLE
add option to add failure data

### ISSUE THREAD

**Issue by eplaut** [getslash/backslash#16]
Hi,
I would like to be able to add an exception data to a failed test without increment the error number.
right now the only why is to use ```api/add_test_error_data```, but it will increse the error_num, and put the exception in the error section, and not in the failure one.

**Comment by vmalloc** [comment]
Would metadata be enough for this? it will not be registered as error, but it will be availble for viewing in the test page...

**Comment by vmalloc** [comment]
new backslash supports metadata and test details, so it can be used for this purpose
