### ISSUE TITLE
Installtion with docker-compose failed

### ISSUE THREAD

**Issue by eplaut** [getslash/backslash#226]
on release 2.7.1, [docker/Dockerfile](https://github.com/getslash/backslash/blob/develop/docker/Dockerfile#L1). looks like the syntax `as XXXX` is not supported [docker docs](https://docs.docker.com/engine/reference/builder/#from)

error message:
`"node:7 as frontend-builder" is not a valid repository/tag: invalid reference format`

**Comment by eplaut** [comment]
ok, I'm sure we are not using same version (since ` COPY --from=frontend-builder /frontend/dist /src/webapp/dist` failed too `ERROR: Service 'webapp' failed to build: Unknown flag: from`)
```
$ docker --version
Docker version 17.03.1-ce, build c6d412e

$ docker-compose --version
docker-compose version 1.13.0, build 1719ceb
```

**Comment by vmalloc** [comment]
@eplaut it requires docker 17.05 or newer

**Comment by vmalloc** [comment]
@eplaut also please note that there's no automatic migration from earlier versions to docker. A db dump and restore is needed

**Comment by eplaut** [comment]
Thanks! I will try again with docker 17.05

thanks about the DB notice, I think i will leave the old one on different server.
