### ISSUE TITLE
Consider activity as keepalive extension on sessions and tests

### ISSUE THREAD

**Issue by vmalloc** [getslash/backslash#273]

**Comment by vmalloc** [comment]
@ayalash do you happen to remember what we meant by this?

**Comment by ayalash** [comment]
@vmalloc If I remember correctly, we had a session which was marked abandoned but it send "test end" and "test end" events.

**Comment by vmalloc** [comment]
Ooooh right.

**Comment by vmalloc** [comment]
It appears like currently this is handled correctly, although temporarily (while the session is still running) it can show up as abandoned if the keepalive thread dies unexpectedly. This is supposed to be settled once the session sends `session_end` to the server.
