### ISSUE TITLE
UI Overhaul

### ISSUE THREAD

**Issue by vmalloc** [getslash/backslash#283]
- [x] application template
- [x] login template
- [x] Session view/sidebar
- [x] reintroduce pagination controls
- [x] reintroduce filter controls
- [x] make sure filters, pagination and num_pages work on all views
  - [x] sessions
  - [x] tests
  - [x] session tests
  - [x] subjects
  - [x] users
- [x] refactor session items
  - [x] User
  - [x] Subjects + version
  - [x] Labels
  - [x] time
  - [x] icons
    - [x] comment(s)
  - [x] reflect status
    - [x] in pdb
    - [x] abandoned/not abandoned
    - [x] interrupted
    - [x] successful / not successful
    - [x] Warnings
- [x] refactor test items
  - [x] first error
  - [x] skip reason
- [x] refactor subject items
- [x] refactor user items
- [x] Display menu
- [x] Keyboard shortcuts won't close
- [x] Comments markdown is broken
- [x] toolbar buttons - replications
- [x] Update status description should be displayed in session view (near the test) instead of in test-info
- [x] Running tests spinner
- [x] Session sidebar
  - [x] Remove sidebar
  - [x] Remove session-overview component
- [x] Fix Travis build
- [x] Test information refactoring
  - [x] Status description
  - [x] star marker
  - [x] metadata
  - [x] git info
  - [x] metadata links in tests
- [x] Related entities (`related_groups` in metadata_table)
- [x] Search results dropdown
  - [x] Tests
  - [x] Sessions
- [x] Search progress is not spinning correctly
- [x] test tags
- [x] tracebacks and errors
  - [x] Loading traceback display
  - [x] No traceback display
- [x] Clicking on labels should search for that label
- [x] Quick view skip reason from test view
- [x] Mobile view should work
- [x] command line is broken
- [x] avatars
- [x] Test tags: exclude key/value from names
- [x] Fix boolean toggles
- [x] self expansion in tracebacks
- [x] slash version
- [x] Test Parameters
  - [x] Ellipsis
  - [x] Popover sizing
  - [x] In overview
- [x] Last comment time and user id (API CHANGE)
- [x] Remove `available_page_sizes` from all places
- [x] Make sure interrupted tests show up as interrupted (see http://backslash-dev/#/sessions/ff3cfc42-4a36-11e9-beca-0050569935b9_0)
- [x] Parallel sessions
- [x] Parameters table incorrectly sized (http://backslash-dev.lab.gdc.il.infinidat.com/#/sessions/e4c325ac-4a4b-11e9-a11d-0242ac110002_2/tests/e4c325ac-4a4b-11e9-a11d-0242ac110002_2_929)
- [x] Interrupted sessions tab bar
- [x] Sorting
  - [x] Users
  - [x] Subjects
- [x] Proxy users
- [x] Do not minimize Session view's display/filter options after every change
- [x] Test errors should be clickable
- [x] Tests with errors should jump to errors directly
- [x] Consider display width for test and session info
- [x] Avatar on mobile
- [x] should_auto_refresh on session view (exception on undefined)
- [x] Check integration (assets served correctly when dockerized)

**Comment by vmalloc** [comment]
- [ ] span.label rename

**Comment by lballan** [comment]
It would be nice if in the new UI, from the session view, the skip reason of skipped tests will be accessible (like the failure reason of failed tests is accessible in the current UI).
