### ISSUE TITLE
Archive for session/test fails

### ISSUE THREAD

**Issue by alonho** [getslash/backslash#29]
Hash: 66985365d199dd104ba8938277cd641e2639d6fc

I run a minified version so the traceback isn't very helpful. It seems ember knows what's wrong though:
"Nothing handled the action 'toggle_archive'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble."

This feature is probably yet to be implemented.

**Comment by vmalloc** [comment]
Fixed in 23f39a4d9e567f559ac9dd5b920c2f87a1f1c0bb

**Comment by alonho** [comment]
Thanks!
