### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ViktorFagerlind** [getslash/backslash#317]
Hi, I'm very interested in using slash+backslash for embedded HW blackbox testing. However, I cannot find any information on how to use backslash. Is there any such information?

**Comment by vmalloc** [comment]
We have created initial docs covering installation and configuration. It is still work in progress, but I'd love to hear what you find missing or needing clarification there: http://backslash.readthedocs.io/en/master/

**Comment by ViktorFagerlind** [comment]
Thanks for the link!

After some headache due to not being at all familiar with docker etc I got the server up and running. My biggest question now is how to connect the test results and logs from slash to the backslash server. But I guess I'll have to wait for the documentation process... :)

**Comment by vmalloc** [comment]
Sorry, the section is there - it was just ommitted from the index (will be fixed in the next release, in the mean time it is in develop):

http://backslash.readthedocs.io/en/develop/client_configuration.html

**Comment by ViktorFagerlind** [comment]
Thanks, great! I will try it out in the week to come...
