### ISSUE TITLE
Synchronize "is_session_abandoned" to elastic-search

### ISSUE THREAD

**Issue by ayalash** [getslash/backslash#443]
When querying tests with backslash's REST API, `is_session_abandoned` field exists, it would be very useful if it will be synchronized to elastic-search as well.

**Comment by ayalash** [comment]
@vmalloc Are you OK with it?

**Comment by vmalloc** [comment]
hmmph, not sure. It's O(N) where N is the number of tests...

**Comment by vmalloc** [comment]
On second thought I think it can be done relatively easily. Leaving open

**Comment by ayalash** [comment]
@vmalloc If you prefer to change this issue to add `is_abandoned` to the session synchronization to elastic search (issue #401), it is good enough for us.

**Comment by maormarcus** [comment]
superseded by issue_401: https://github.com/getslash/backslash/issues/401
