### ISSUE TITLE
Search inside session tests is broken

### ISSUE THREAD

**Issue by vmalloc** [getslash/backslash#489]
For example: https://backslash.infinidat.com/#/sessions/30697bd6-436d-11e9-85e1-0242ac110002_0?page_size=200&search=name%3D%22test_disabled_events%22

**Comment by vmalloc** [comment]
Cannot reproduce for now. In case it pops up again we will reopen.

**Comment by ayalash** [comment]
@vmalloc Reproduced again:
http://backslash-dev.lab.gdc.il.infinidat.com/#/sessions/d1f1b4da-4f0e-11e9-9b14-8cec4b848928_0?search=test_data_rename
