### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by drrlvn** [getslash/backslash#492]
- [x] Improve contrast of borders
- [x] Exceptions should be in monospace font
- [x] Add copy button to variables in backtrace
- [x] Test frame indicator should not have a gradient
- [x] Corners should be round
- [x] Font sizes should be adjusted - some things are very small while others are too large

**Comment by vmalloc** [comment]
Continues #283

**Comment by vmalloc** [comment]
@drrlvn made a few improvements. Regarding font sizes we changed a few of them -- if there's something that still doesn't sit right please open a new issue with more specific pointers to what's broken
