### ISSUE TITLE
Editing another user's preferences changes my own preferences

### ISSUE THREAD

**Issue by lballan** [getslash/backslash#504]
Following the new UI overhaul, if I attempt to edit the preferences of another user, my own preferences are edited instead.

Same goes for unstarring a test that another user starred - if I have also starred it, it will be unstarred for me.

**Comment by vmalloc** [comment]
@lballan you are an admin, right?

**Comment by lballan** [comment]
@vmalloc Correct. before the new UI, I couldn't see other users' preferences at all.
Basically, as I see it, there are two options:
* Giving me (as an admin) the ability to modify preferences of other users
* Forbid modification of other users' preferences

**Comment by vmalloc** [comment]
Yeah, setting preferences for other users has always been possible for admins. The "bug" is that the UI now exposes it. 
I'll make it visible for admins only, and add a warning reminding you that you are fiddling with other users' settings....

**Comment by ayalash** [comment]
@vmalloc I think you misunderstood - Lee tried to change my preferences in the GUI but it changed his own.

**Comment by vmalloc** [comment]
Ah I see. Yes, that makes sense looking at the API. I will change it to hide the pane for other users. It’s a glitch that it shows it anyway.
