### ISSUE TITLE
Newlines are negated in the metadata fields

### ISSUE THREAD

**Issue by yaelmi3** [getslash/backslash#546]
![image](https://user-images.githubusercontent.com/8473096/56665872-8cdd4000-66b3-11e9-9623-6801b30068e5.png)
Newlines ('\n') are ignored in the metadata fields (i.e. docstring).
This is a regression from a previous backslash release 
![image](https://user-images.githubusercontent.com/8473096/56665998-c7df7380-66b3-11e9-90b0-2a53d90ec11a.png)

**Comment by vmalloc** [comment]
Example: b8f4d6b6-66a0-11e9-8394-8c8590c28c4f_0_2
