### ISSUE TITLE
Add is_fatal indication for errors

### ISSUE THREAD

**Issue by ayalash** [getslash/backslash#563]
Currently, when a session is marked as fatal, there is no way from backslash to know which error cause it.

It would be very helpful if errors will have 'is_fatal' boolean field (nullable for backwards compatibility) & 'fatal' badge on GUI (similar to session's one) in case this field is True.

**Comment by ayalash** [comment]
@vmalloc Any objections?

**Comment by ayalash** [comment]
Relates to: https://github.com/getslash/backslash-python/issues/101

**Comment by vmalloc** [comment]
Oh now I see - forget my comment on the related issue.

Sure - no objections
