### ISSUE TITLE
Replication converts integer and float test details to strings

### ISSUE THREAD

**Issue by bpowell65536** [getslash/backslash#585]
When the following test code is run:

```
from backslash.contrib.slash_plugin import BackslashPlugin
import slash


slash.plugins.manager.install(BackslashPlugin(url=...), activate=True, is_internal=True)


def test_serialisation():
    slash.context.result.details.set("int_detail", 1234)
    slash.context.result.details.set("float_detail", 98.765)
```

`int_detail` and `float_detail` are stored using the correct types in the Backslash database, but when the database is replicated to Elasticsearch, these details get turned into strings. This looks like the intended behaviour given the changes made for #395, but converting integer and float details to strings when storing them in the Elasticsearch database makes any analysis involving those details difficult. Could an exception for integer and float types be added to the code which converts test and session details to strings, or will this break other parts of the system?

Slash version: 1.8.0
Backslash Python client version: 2.39.0
Backslash version: 2.17.2 (UI 2.17.2)

**Comment by vmalloc** [comment]
The problem is not necessarily with integers and strings - the problem is ES itself -- once a value is stored in a certain type, any future attempts to store a different type under the same key would fail the replication miserably, rendering the replication useless... The only workaround we found for this is converting everything in dynamic segments (e.g. details and extra info/metadata) to be strings when replicating...

**Comment by bpowell65536** [comment]
OK, I think I understand the problem - the structure of a test record as sent to Elasticsearch removes any information about what test a particular detail is associated with, so another test re-using the detail name later for a detail of a different type would break things. Is this correct?

**Comment by vmalloc** [comment]
yes. details is a nested structure of "test", meaning it is treated like a field. If one test contains details.x=2 and another contains details.x="hello", replication would fail with an exception...

**Comment by bpowell65536** [comment]
I see. It looks like I will have to find another way to do what I am trying to do. Thanks for your help :)
