### ISSUE TITLE
WEB?

### ISSUE THREAD

**Issue by QwistyS** [getslash/backslash#616]
Hi, I have an issue with accessing the WEB page.
After following the installation guide "https://backslash.readthedocs.io/en/latest/installation.html#step-4-start-backslash"
How do I access the web page?

Thank you in advance.

Service status:
===========================================================
 backslash-docker.service - Backslash test reporting service
 Loaded: loaded (/etc/systemd/system/backslash-docker.service; enabled; vendor preset: enabled)
 Active: active (exited) since Thu 2020-09-24 14:47:48 IDT; 16min ago
 Process: 20685 ExecStop=/usr/bin/docker-compose -f docker-compose.yml -p backslash down (code=exited, status=0/SUCCESS)
 Process: 21182 ExecStart=/usr/bin/docker-compose -f docker-compose.yml -p backslash up -d (code=exited, status=0/SUCCESS)
 Process: 21149 ExecStartPre=/usr/bin/docker-compose -f docker-compose.yml -p backslash down (code=exited, 
 status=0/SUCCESS)
 Main PID: 21182 (code=exited, status=0/SUCCESS)

Sep 24 14:47:30 ci_backslash_reports docker-compose[21182]: [78B blob data]
Sep 24 14:47:30 ci_backslash_reports docker-compose[21182]: Creating backslash_monitor_1
Sep 24 14:47:36 ci_backslash_reports docker-compose[21182]: [248B blob data]
Sep 24 14:47:36 ci_backslash_reports docker-compose[21182]: Creating backslash_python-backend-api_1
Sep 24 14:47:39 ci_backslash_reports docker-compose[21182]: [155B blob data]
Sep 24 14:47:39 ci_backslash_reports docker-compose[21182]: Creating backslash_python-backend-ui_1
Sep 24 14:47:43 ci_backslash_reports docker-compose[21182]: [91B blob data]
Sep 24 14:47:43 ci_backslash_reports docker-compose[21182]: Creating backslash_nginx_1
Sep 24 14:47:48 ci_backslash_reports docker-compose[21182]: [49B blob data]
Sep 24 14:47:48 ci_backslash_reports systemd[1]: Started Backslash test reporting service.
===========================================================

**Comment by vmalloc** [comment]
Can you reach http://127.0.0.1:8000?

**Comment by QwistyS** [comment]
> Can you reach http://127.0.0.1:8000?

Hi... sir
Yes, I can, but it's stuck on "Loading... Please wait"

**Comment by vmalloc** [comment]
I'm guessing there's some hidden error or exception here. Please see the console logs on your browser (a.k.a the developer console), and take a look at the logs for the api backend (through docker logs on the relevant container)

**Comment by QwistyS** [comment]
> I'm guessing there's some hidden error or exception here. Please see the console logs on your browser (a.k.a the developer console), and take a look at the logs for the api backend (through docker logs on the relevant container)

Sir, you are correct.
![image](https://user-images.githubusercontent.com/30431487/94145784-bdfb0a80-fe7b-11ea-983a-5a53c02744d4.png)

seems like I have a Proxy issue, do you have a configuration for that?

**Comment by vmalloc** [comment]
this is not the actual error - the errors are probably in the "requests" or "network" section of your console

**Comment by QwistyS** [comment]
> this is not the actual error - the errors are probably in the "requests" or "network" section of your console

![image](https://user-images.githubusercontent.com/30431487/94148864-d9681480-fe7f-11ea-92df-c8eaf192b671.png)

**Comment by QwistyS** [comment]
sudo systemctl status backslash-docker.service
[sudo] password for administrator:
● backslash-docker.service - Backslash test reporting service
   Loaded: loaded (/etc/systemd/system/backslash-docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-09-29 17:08:59 IDT; 45s ago
  Process: 1306 ExecStart=/usr/local/bin/docker-compose -f docker-compose.yml -p backslash up -d (code=exited, status=255)
  Process: 793 ExecStartPre=/usr/local/bin/docker-compose -f docker-compose.yml -p backslash down (code=exited, status=255)
 Main PID: 1306 (code=exited, status=255)

Sep 29 17:08:59 perclnx docker-compose[1306]:   File "compose/cli/command.py", line 69, in project_from_options
Sep 29 17:08:59 perclnx docker-compose[1306]:   File "compose/cli/command.py", line 132, in get_project
Sep 29 17:08:59 perclnx docker-compose[1306]:   File "compose/cli/docker_client.py", line 43, in get_client
Sep 29 17:08:59 perclnx docker-compose[1306]:   File "compose/cli/docker_client.py", line 170, in docker_client
Sep 29 17:08:59 perclnx docker-compose[1306]:   File "docker/api/client.py", line 188, in __init__
Sep 29 17:08:59 perclnx docker-compose[1306]:   File "docker/api/client.py", line 213, in _retrieve_server_version
Sep 29 17:08:59 perclnx docker-compose[1306]: **docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))**
Sep 29 17:08:59 perclnx systemd[1]: backslash-docker.service: Main process exited, code=exited, status=255/n/a
Sep 29 17:08:59 perclnx systemd[1]: backslash-docker.service: Failed with result 'exit-code'.

**Comment by QwistyS** [comment]
$ sudo docker logs --details 949387dbc05a
IMAGE_NAME=getslash%2Fbackslash 2020/09/29 15:38:00 Waiting for host: python-backend-api:8000
IMAGE_NAME=getslash%2Fbackslash 2020/09/29 15:38:00 Waiting for host: python-backend-ui:8000
IMAGE_NAME=getslash%2Fbackslash 2020/09/29 15:38:00 Waiting for host: api-server:8000
IMAGE_NAME=getslash%2Fbackslash 2020/09/29 15:38:00 Received 200 from http://api-server:8000/metrics
IMAGE_NAME=getslash%2Fbackslash 2020/09/29 15:38:00 Received 200 from http://api-server:8000/metrics
IMAGE_NAME=getslash%2Fbackslash 2020/09/29 15:38:00 Received 200 from http://api-server:8000/metrics
IMAGE_NAME=getslash%2Fbackslash 2020/09/29 15:38:11 **[error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "POST /api/get_ap                  p_config HTTP/1.1", upstream: "http://172.18.0.8:8000/api/get_app_config", host: "127.0.0.1:8000", referrer: "http://127.0.0.1:8000/"**
IMAGE_NAME=getslash%2Fbackslash 172.18.0.1 - - [29/Sep/2020:15:38:11 +0000] "POST /api/get_app_config HTTP/1.1" 502 157 0.000 0.000 .
$ telnet 172.18.0.1 8000
Trying 172.18.0.1...
**Connected to 172.18.0.1.**
Escape character is '^]'.
^
HTTP/1.1 400 Bad Request
Server: nginx/1.17.2
Date: Tue, 29 Sep 2020 15:39:47 GMT
Content-Type: text/html
Content-Length: 157
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.17.2</center>
</body>
</html>
Connection closed by foreign host.
administrator@perclnx:~$
