### ISSUE TITLE
Error scrollbar behaves differently between Firefox and Chrome

### ISSUE THREAD

**Issue by vmalloc** [getslash/backslash#76]
Migrated from BACKSLASH-169

**Comment by ayalash** [comment]
BACKSLASH-169 description:
> When drilling down into errors and when the output long, there is a horizontal scrollbar.
> In Chrome, clicking on the moving part of the SB and moving it, scrolls.
> In FF, doing it tries to drag the whole div. To scroll, I need to click on an empty area in the scrollbar.

I checked with Firefox, this is no longer the behavior.
